name: 🐛 Bug Report
description: Report a bug or issue with bloc_meta or bloc_meta_generator
title: "[BUG]: "
labels: ["bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the form below to help us understand and fix the issue.

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      options:
        - bloc_meta
        - bloc_meta_generator
        - Both
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of the package are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Add annotation '...'
        2. Run build_runner '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: dart
      placeholder: |
        import 'package:bloc_meta/bloc_meta.dart';
        
        @BlocMeta<MyEvent, MyState>()
        final class MyBloc extends _$MyBloc {
          // Your code here
        }
    validations:
      required: false

  - type: textarea
    id: generated
    attributes:
      label: Generated Code (if applicable)
      description: If the issue is with code generation, please paste the generated code
      render: dart
      placeholder: Paste the generated .g.dart file content here...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages or stack traces
      render: shell
      placeholder: Paste error logs here...
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your development environment
      value: |
        - Dart SDK version: 
        - Flutter version (if applicable): 
        - Operating System: 
        - IDE: 
        - build_runner version: 
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues to avoid duplicates
          required: true
        - label: I have provided a minimal reproducible example
          required: false
        - label: I am using the latest version of the package
          required: false
