name: ❓ Question
description: Ask a question about bloc_meta or bloc_meta_generator
title: "[QUESTION]: "
labels: ["question", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please fill out the form below.
        
        **Note:** For general BLoC questions unrelated to bloc_meta, please use the [BLoC Discord](https://discord.gg/bloc) or [Stack Overflow](https://stackoverflow.com/questions/tagged/flutter-bloc).

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is your question about?
      options:
        - bloc_meta
        - bloc_meta_generator
        - Both
        - General
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or background information
      placeholder: I'm trying to... and I'm not sure how to...
    validations:
      required: false

  - type: textarea
    id: code
    attributes:
      label: Code Sample (if applicable)
      description: Provide a code sample related to your question
      render: dart
      placeholder: |
        @BlocMeta<MyEvent, MyState>()
        final class MyBloc extends _$MyBloc {
          // Your code here
        }
    validations:
      required: false

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What have you already tried to solve this?
      placeholder: I've tried...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the question here
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have read the documentation
          required: true
        - label: I have searched for existing issues and discussions
          required: true
        - label: This question is specific to bloc_meta/bloc_meta_generator
          required: true
