targets:
  $default:
    builders:
      bloc_annotation_generator:
        enabled: true

builders:
  bloc_annotation_generator:
    import: "package:bloc_annotation_generator/builder.dart"
    builder_factories: ["blocAnnotationGenerator"]
    build_extensions: { ".dart": [".bloc_annotation_generator.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]